### ISSUE TITLE
This repo is still alive?

### ISSUE THREAD

**Issue by tosone** [giorgisio/goav#36]

**Comment by tosone** [comment]
https://github.com/selfmodify/goav i find this repo is still alive. And support the latest ffmpeg though lots of warnings.

**Comment by asticode** [comment]
Hey guys,

Just to let you know that since I was having problems with the repo mentionned above I've also forked the project to propose bindings compatible with ffmpeg 4.0.2:

https://github.com/asticode/goav

If you're interested why:

1) [the base project](https://github.com/giorgisio/goav) is not maintained anymore
2) [this project](https://github.com/targodan/ffgopeg) is a hard fork of #1 but has gone a very different route
3) [this project](https://github.com/selfmodify/goav) is a fork of #1 but I'm experiencing lots of panics 
4) [this project](https://github.com/amarburg/goav) is the best fork of #1 even though the last commit is not recent
5) [this project](https://github.com/ioblank/goav) is a fork of #4 with interesting additional commits
6) [this project](https://github.com/koropets/goav) is a fork of #4 with interesting additional commits

Therefore I've forked #4 and I've cherry-picked interesting commits of #5 and #6.

Let me know if you run into issues.
Cheers

**Comment by corebreaker** [comment]
Hello, @giorgisio , we'd like to contribute, but it's true, it's slow to have PR merged. Recently, there is a big problem the compatibility with the recent version of av* libraries. A solution could be to designate a delegator among the contributors and allow him to merge for you.

Regards.

**Comment by corebreaker** [comment]
Hi @giorgisio , i just pushed a PR (the #38) which resolve all compilation problems, and with it a program can be built with libs v3 and v4.

Regards.

**Comment by giorgisio** [comment]
@corebreaker Merged. Thanks.
