### ISSUE TITLE
Which ffpmeg version is used?

### ISSUE THREAD

**Issue by lovelly** [giorgisio/goav#37]
Which ffpmeg version to use, I use the 4.1 version to get avcodec.Contex is nil

**Comment by asticode** [comment]
@lovelly I don't really know which ffmpeg version the `master` branch is currently supporting but for sure it doesn't support `4.1`.

Some PRs have been made to fix that but they've not been accepted yet.

Otherwise I've forked the projet, merged interesting changes from other forks and added my own if you're interested: https://github.com/asticode/goav. It supports `4.0.2` which should be enough for `4.1`.

**Comment by giorgisio** [comment]
A few PRs are now merged.
